# Generated by Django 2.2.28 on 2024-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_featureapi', '0004_remove_restapi_refs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureversions',
            name='feat_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
