# Generated by Django 2.2.18 on 2021-10-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0005_etlworkspaces_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etlworkspaces',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
