# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-03 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0003_baselayer_baselayerproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselayer',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
