# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0005_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlayergroup',
            name='layer_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.LayerGroup'),
        ),
    ]
