# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0015_auto_20190710_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_project_icon',
            field=models.BooleanField(default=True),
        ),
    ]
