# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-07 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0025_update_main_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBaseLayerTiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.IntegerField(default=0)),
                ('levels', models.IntegerField(default=0)),
                ('tilematrixset', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('extentid', models.CharField(max_length=50)),
                ('version', models.BigIntegerField(blank=True, null=True)),
                ('folder_prj', models.CharField(max_length=1024)),
                ('running', models.BooleanField(default=False)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.Project')),
            ],
        ),
    ]
