# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-02-02 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0032_auto_20210201_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilingprocessstatus',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tilingprocessstatus',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
