# Generated by Django 2.2.18 on 2021-02-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='type',
            field=models.CharField(default='barchart', max_length=25),
        ),
    ]
