# Generated by Django 2.2.27 on 2022-10-27 11:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('fields', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('usr', models.CharField(default='', max_length=150)),
                ('feat_id', models.IntegerField(default=0)),
                ('operation', models.IntegerField(default=1)),
                ('resource', models.CharField(max_length=500, null=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Layer')),
            ],
        ),
    ]
