# Generated by Django 2.2.18 on 2023-01-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0009_etlworkspaces_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='segex_FechaFinGarantizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField(null=True)),
                ('entity', models.CharField(max_length=250)),
                ('type', models.IntegerField()),
                ('fechafingarantizada', models.DateTimeField()),
            ],
        ),
    ]
