# Generated by Django 2.2.28 on 2023-06-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0014_etlworkspaces_concat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etlstatus',
            name='id_ws',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
