# Generated by Django 2.2.28 on 2024-02-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0021_sendemails_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlWorkspaceEditRestrictedRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('etl_ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_geoetl.ETLworkspaces')),
            ],
        ),
        migrations.AddIndex(
            model_name='etlworkspaceeditrestrictedrole',
            index=models.Index(fields=['etl_ws', 'role'], name='gvsigol_plu_etl_ws__4d292b_idx'),
        ),
        migrations.AddConstraint(
            model_name='etlworkspaceeditrestrictedrole',
            constraint=models.UniqueConstraint(fields=('etl_ws', 'role'), name='unique_restricted_edit_permission_per_role_and_etlws'),
        ),
    ]
