# Generated by Django 2.2.28 on 2024-04-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0022_auto_20240214_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlstatus',
            name='last_exec',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
