# Generated by Django 2.2.28 on 2026-02-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0029_migrate_database_connections_to_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='database_connections',
        ),
    ]
