# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-01 07:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_worldwind', '0004_auto_20190930_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldwindprovider',
            name='layers',
            field=models.CharField(blank=True, default='elevation', max_length=250, null=True),
        ),
    ]
