# Generated by Django 2.2.27 on 2022-10-27 11:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    dependencies = [
        ('gvsigol_plugin_featureapi', '0001_initial'),
    ]

    def copy_data(apps, schema_editor):
        # No se puede hacer así pq necesitamos restapi instalado 
        # FeatureVersions = apps.get_model("gvsigol_plugin_featureapi", "FeatureVersions")
        # FeatureChange = apps.get_model("gvsigol_plugin_restapi", "FeatureChange")
        # FeatureVersions.objects.bulk_create(FeatureChange.objects.all())
        
        # migrations.RunSQL([(
        #     "INSERT INTO gvsigol_plugin_featureapi_featureversions \
        #     (id, version, wkb_geometry, fields, date, usr, feat_id, operation, resource, layer_id) \
        #     VALUES(0, 1, 'MULTIPOINT ((-0.33 39.44))', '{u'campo1': u'19', u'feat_date_gvol': u'2021-01-14T13:23:34.997986+01:00'}','2021-01-14 13:23:35', 'nbrodin', 18, 1, NULL, 166 )"
        #     , None)]
        #     #SELECT id, version, wkb_geometry, fields, date, usr, feat_id, operation, resource, layer_id FROM gvsigol_plugin_restapi_featurechange;
        # )
        pass
    

    operations = [
        migrations.RunSQL(
            "INSERT INTO public.gvsigol_plugin_featureapi_featureversions \
            (id, version, wkb_geometry, fields, date, usr, feat_id, operation, resource, layer_id) \
            SELECT id, version, wkb_geometry, fields, date, usr, feat_id, operation, resource, layer_id FROM public.gvsigol_plugin_restapi_featurechange"
        )
        #migrations.RunPython(copy_data, reverse_code=migrations.RunPython.noop),
    ]
