# Generated by Django 2.2.28 on 2025-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0049_project_viewer_default_crs'),
        ('gvsigol_plugin_geocoding', '0002_auto_20190517_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='providers', to='gvsigol_core.Project'),
        ),
    ]
