# Generated by Django 2.2.18 on 2022-07-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_filemanager', '0002_auto_20220719_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exports_historical',
        ),
    ]
