# Generated by Django 2.2.18 on 2022-07-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_filemanager', '0004_exports_historical'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exports_historical',
        ),
    ]
