# Generated by Django 2.2.28 on 2023-04-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_filemanager', '0004_exports_historical_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exports_historical',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exports_historical',
            name='redirect',
            field=models.TextField(blank=True, null=True),
        ),
    ]
