# Generated by Django 2.2.18 on 2022-07-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_filemanager', '0006_exports_historical'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exports_historical',
            new_name='exports_historica',
        ),
    ]
