# Generated by Django 2.2.18 on 2022-07-19 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_filemanager', '0011_auto_20220719_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exports_historical',
            name='datetime',
        ),
        migrations.AddField(
            model_name='exports_historical',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exports_historical',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
