# Generated by Django 2.2.28 on 2024-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentiloConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('sentilo_identity_key', models.CharField(max_length=200)),
                ('tabla_de_datos', models.CharField(max_length=200)),
                ('sentilo_sensors', models.TextField()),
                ('intervalo_de_actualizacion', models.IntegerField()),
            ],
        ),
    ]
