# Generated by Django 2.2.28 on 2025-09-09 10:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gvsigol_core', '0049_project_viewer_default_crs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDisplayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.Project', verbose_name='Proyecto')),
                ('layer_configs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Configuración de capas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),                
            ],
            options={
                'verbose_name': 'Configuración Media Display',
                'verbose_name_plural': 'Configuraciones Media Display',
            },
        ),
    ]
