# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-31 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_symbology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linesymbolizer',
            name='stroke_dash_array',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksymbolizer',
            name='stroke_dash_array',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polygonsymbolizer',
            name='stroke_dash_array',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
