# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-17 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_symbology', '0003_auto_20170605_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsymbolizer',
            name='anchor_point_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='textsymbolizer',
            name='anchor_point_y',
            field=models.FloatField(default=-1.5),
        ),
    ]
