# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-12 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_symbology', '0008_auto_20171212_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='custom_legend_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='has_custom_legend',
            field=models.BooleanField(default=False),
        ),
    ]
