# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-02 11:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_symbology', '0009_auto_20180212_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='sld',
            field=models.TextField(blank=True, null=True),
        ),
    ]
