# Generated by Django 2.2.28 on 2026-01-19 07:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0083_wmts_options_bis'),
        ('gvsigol_symbology', '0010_style_sld'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapboxStyleCache',
            fields=[
                ('layer', models.OneToOneField(help_text='Capa a la que pertenece esta caché', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mapbox_cache', serialize=False, to='gvsigol_services.Layer')),
                ('json_cache', django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON completo con tile_url, source_layer y styles[]')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la caché')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización de la caché')),
            ],
            options={
                'verbose_name': 'Mapbox Style Cache',
                'verbose_name_plural': 'Mapbox Style Caches',
            },
        ),
    ]
