# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-07 10:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0002_workspace_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='temporary_endfield',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='temporary_field',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
