# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-16 11:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0005_auto_20170816_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='time_resolution',
        ),
        migrations.AddField(
            model_name='layer',
            name='time_resolution_day',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_resolution_hour',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_resolution_minute',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_resolution_month',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_resolution_second',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_resolution_week',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_resolution_year',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
