# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-21 15:28


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0006_auto_20170816_1125'),
        ('gvsigol_services', '0003_auto_20170814_1041'),
    ]

    operations = [
    ]
