# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-03 09:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0013_workspace_wmts_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/static/img/no_thumbnail.jpg', null=True, upload_to='thumbnails'),
        ),
    ]
