# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-03 10:23


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0014_auto_20190403_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=500)),
                ('is_master', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(choices=[('geoserver', 'geoserver'), ('mapserver', 'mapserver')], default='geoserver', max_length=50)),
                ('frontend_url', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='layergroup',
            name='workspace_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/gvsigonline/static/img/no_thumbnail.jpg', null=True, upload_to='thumbnails'),
        ),
        migrations.AddField(
            model_name='node',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Server'),
        ),
    ]
