# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-03 12:18


from django.db import migrations, models
import django.db.models.deletion
import gvsigol_services.models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0016_default_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='server',
            field=models.ForeignKey(default=gvsigol_services.models.get_default_server, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Server'),
        ),
    ]
