# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-17 13:09


from django.db import migrations, models
import gvsigol_services.models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0018_auto_20190506_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='thumbnail',
            field=models.ImageField(blank=True, default=gvsigol_services.models.get_default_layer_thumbnail, null=True, upload_to='thumbnails'),
        ),
    ]
