# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-27 16:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0019_auto_20190517_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='highlight_scale',
        ),
        migrations.AddField(
            model_name='layer',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='external_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='abstract',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='layer',
            name='datastore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Datastore'),
        ),
    ]
