# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-07-10 10:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0021_baselayer_to_externallayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='allow_download',
            field=models.BooleanField(default=True),
        ),
    ]
