# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-05 16:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0025_layerfieldenumeration_multiple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerfieldenumeration',
            name='lyrid',
        ),
    ]
