# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-27 15:17


from django.db import migrations, models
import django.db.models.deletion
from django.contrib.gis.gdal import layer

def fill_layer_field(apps, schema_editor):
    try:
        LayerFieldEnumeration = apps.get_model("gvsigol_services", "LayerFieldEnumeration")
        Layer = apps.get_model("gvsigol_services", "Layer")

        for lf_enum in LayerFieldEnumeration.objects.all():
            try:
                layer = Layer.objects.get(name=lf_enum.layername, datastore__name=lf_enum.schema)
                lf_enum.layer = layer
                lf_enum.save()
            except Exception as error:
                print("\n    ** Error gvsigol: Error asignando Layer a LayerFieldEnumeration en el campo layer")
                print(lf_enum.pk)
                print(lf_enum.layername)
                print(lf_enum.schema)
                print(error)
    except Exception as error:
        print("\n    ** Error gvsigol: Error asignando Layer a LayerFieldEnumeration en el campo layer")
        print(error)


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0033_layer_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerfieldenumeration',
            name='layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Layer'),
        ),
        migrations.RunPython(fill_layer_field, reverse_code=migrations.RunPython.noop),
    ]
