# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-21 13:05


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0037_layer_source_name_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=150)),
                ('layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField(unique=True)),
                ('func_name', models.CharField(max_length=150)),
                ('func_schema', models.CharField(max_length=150)),
                ('label', models.CharField(max_length=150)),
                ('definition_tpl', models.TextField(blank=True, null=True)),
                ('activation', models.CharField(max_length=10)),
                ('event', models.CharField(max_length=100)),
                ('orientation', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='trigger',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.TriggerProcedure'),
        ),
    ]
