# Generated by Django 2.2.21 on 2022-01-05 16:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0052_fix_triggers_python3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('json_def', django.contrib.postgres.fields.jsonb.JSONField()),
                ('datastore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Datastore')),
            ],
        ),
    ]
