# Generated by Django 2.2.27 on 2022-03-28 14:47

from django.db import migrations

def groups_to_roles(apps, schema_editor):
    LayerReadGroup = apps.get_model("gvsigol_services", "LayerReadGroup")
    LayerWriteGroup = apps.get_model("gvsigol_services", "LayerWriteGroup")
    LayerReadRole = apps.get_model("gvsigol_services", "LayerReadRole")
    LayerWriteRole = apps.get_model("gvsigol_services", "LayerWriteRole")
    for lyr_rug in LayerReadGroup.objects.all():
        try:
            if lyr_rug.group:
                lyr_read_role = LayerReadRole(
                    layer=lyr_rug.layer,
                    role=lyr_rug.group.name
                )
                lyr_read_role.save()
        except Exception as e:
            print(str(e))
    for lyr_wug in LayerWriteGroup.objects.all():
        try:
            if lyr_wug.group:
                lyr_write_role = LayerWriteRole(
                    layer=lyr_wug.layer,
                    role=lyr_wug.group.name
                )
                lyr_write_role.save()
        except Exception as e:
            print(str(e))

class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_auth', '0005_groups_to_roles'),
        ('gvsigol_services', '0055_auto_20220330_0929'),
    ]

    operations = [
        migrations.RunPython(groups_to_roles, reverse_code=migrations.RunPython.noop),
    ]
