# Generated by Django 2.2.28 on 2023-07-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0057_golfunc_area_m2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultUserDatastore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('datastore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Datastore')),
            ],
        ),
    ]
