# Generated by Django 2.2.28 on 2023-09-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0060_auto_20230913_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerGroupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('permission', models.TextField(choices=[('manage', 'manage')], default='manage')),
                ('layergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.LayerGroup')),
            ],
        ),
        migrations.DeleteModel(
            name='LayerGroupManageRole',
        ),
        migrations.AddIndex(
            model_name='layergrouprole',
            index=models.Index(fields=['layergroup', 'permission', 'role'], name='gvsigol_ser_layergr_29a5de_idx'),
        ),
    ]
