# Generated by Django 2.2.28 on 2023-10-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0062_auto_20231002_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergrouprole',
            name='permission',
            field=models.TextField(choices=[('manage', 'manage'), ('includeinprojects', 'includeinprojects')], default='manage'),
        ),
    ]
