# Generated by Django 2.2.28 on 2023-11-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0063_auto_20231006_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='layer',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
