# Generated by Django 2.2.28 on 2025-09-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0075_add_favorite_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumeration',
            name='order_type',
            field=models.TextField(blank=True, choices=[('alphabetical', 'Alphabetical'), ('manual', 'Manual')], default='manual'),
        ),
    ]
