# Generated by Django 2.2.18 on 2022-07-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exports_historical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('file', models.CharField(max_length=250)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('redirect', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
