# Generated by Django 2.2.18 on 2023-04-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_filemanager', '0003_auto_20220720_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='exports_historical',
            name='task_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
