# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 18:04


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0004_auto_20190924_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadlink',
            old_name='prepared_download',
            new_name='prepared_download_path',
        ),
        migrations.RemoveField(
            model_name='downloadlink',
            name='id',
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='contents',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gvsigol_plugin_downloadman.DownloadRequest'),
        ),
    ]
