# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 11:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0010_auto_20191030_1113'),
    ]

    operations = [
        migrations.DeleteModel('DownloadLog'),
        migrations.DeleteModel('ResourceLocator'),
        migrations.DeleteModel('DownloadLink'),
        migrations.DeleteModel('DownloadRequest'),
    ]
