# Generated by Django 2.2.21 on 2021-09-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_auth', '0002_fix_admin_usergrup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
