# Generated by Django 2.2.28 on 2026-01-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_auth', '0007_filluserproperties'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(unique=True)),
                ('searchable_text', models.TextField(blank=True)),
                ('searchable_data', models.TextField(blank=True)),
                ('username', models.TextField(unique=True)),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('roles', models.TextField(blank=True)),
                ('editable', models.BooleanField(default=True)),
            ],
        ),
    ]
