# Generated by Django 2.2.28 on 2026-02-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_auth', '0010_gin_trigram_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
