# Generated by Django 2.2.28 on 2026-01-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_symbology', '0011_mapboxstylecache'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mapboxstylecache',
            table=None,
        ),
    ]
