# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-05 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0012_auto_20190527_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlayergroup',
            name='default_baselayer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
