# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0014_auto_20190402_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=500)),
                ('is_master', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='frontend_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='node',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Server'),
        ),
    ]
