# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-03 10:34
from __future__ import unicode_literals

from django.db import migrations, models
from gvsigol import settings
try:
    from gvsigol.settings import GVSIGOL_SERVICES as LEGACY_GVSIGOL_SERVICES
except:
    try:
        from gvsigol.settings import LEGACY_GVSIGOL_SERVICES
    except:
        LEGACY_GVSIGOL_SERVICES = None

def create_default_server(apps, schema_editor):
    try:
        if LEGACY_GVSIGOL_SERVICES and LEGACY_GVSIGOL_SERVICES.get("URL"):
            Server = apps.get_model("gvsigol_services", "Server")
            if Server.objects.count() == 0:
                server = Server()
                server.name = 'defaultgeoserver'
                server.title = 'default geoserver'
                server.description = 'Autogenerated by migrations'
                server.frontend_url = LEGACY_GVSIGOL_SERVICES.get("URL", "")
                server.user = LEGACY_GVSIGOL_SERVICES.get("USER", "")
                server.password = LEGACY_GVSIGOL_SERVICES.get("PASSWORD", "")
                server.default = True
                server.save()
                
                Node = apps.get_model("gvsigol_services", "Node")
                node = Node()
                node.server = server
                node.status = 'active';
                node.url = server.frontend_url
                node.is_master = True
                node.save()
                return
        print "\n    ** Aviso gvsigol: no se creará un Server por defecto. Añada LEGACY_GVSIGOL_SERVICES a settings si es necesario"
    except Exception as error:
        print "\n    ** Error gvsigol: Error creando Server por defecto:"
        print error

class Migration(migrations.Migration):

    dependencies = [
         ('gvsigol_services', '0015_auto_20190503_1023'),
    ]

    operations = [
        migrations.RunPython(create_default_server, reverse_code=migrations.RunPython.noop),
    ]
