# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-17 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0015_auto_20190409_0946'),
        ('gvsigol_services', '0014_auto_20190403_0938'),
    ]

    operations = [
    ]
