# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-18 08:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0016_project_show_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selectable_groups',
            field=models.BooleanField(default=False),
        ),
    ]
