# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-17 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0017_auto_20190417_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layergroup',
            name='workspace',
        ),
        migrations.AddField(
            model_name='layergroup',
            name='workspace_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
