# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-14 15:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0021_sharedview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='baselayer_version',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
