# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0028_layer_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='default_srs',
            field=models.CharField(default='EPSG:4326', max_length=100),
        ),
    ]
