# Generated by Django 2.2.21 on 2021-11-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0037_auto_20210310_1250'),
        ('gvsigol_core', '0035_projectzone_zonelayers'),
    ]

    operations = [
    ]
