# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-20 14:47


from django.db import migrations
from gvsigol_services.triggers import INVERSE_GEOCODER_CARTOCIUDAD_FUNCTION_SIGNATURE, INVERSE_GEOCODER_CARTOCIUDAD_FUNCTION_NAME, INVERSE_GEOCODER_CARTOCIUDAD_FUNCTION_SCHEMA, INVERSE_GEOCODER_CARTOCIUDAD_DEF, InverseGeocoderCartociudad, drop_procedure
import json, psycopg2

TRIGGER_SIGNATURE = INVERSE_GEOCODER_CARTOCIUDAD_FUNCTION_SIGNATURE
FUNCTION_DEF_REVERSE = "DROP FUNCTION IF EXISTS " + TRIGGER_SIGNATURE


def get_db_connection(datastore):
    """
    Obtiene una conexión de introspección a la base de datos.
    Soporta tanto el modo legacy como el nuevo modelo de conexiones.
    """
    params = json.loads(datastore.connection_params) if datastore.connection_params else {}
    
    
    host = params.get('host', 'localhost')
    port = params.get('port', '5432')
    dbname = params.get('database', '')
    user = params.get('user', '')
    passwd = params.get('passwd', params.get('password', ''))
    
    conn = psycopg2.connect(database=dbname, user=user, password=passwd, host=host, port=port, connect_timeout=5)
    conn.set_isolation_level(psycopg2.extensions.ISOLATION_LEVEL_AUTOCOMMIT)
    return conn

def install_procedure(apps, definition):
    """
    Installs the procedure on the database referenced by the cursor.
    If cursor is not provided, the procedure is installed in the database
    of all the available datastores
    """
    Datastore = apps.get_model("gvsigol_services", "Datastore")
    for store in Datastore.objects.filter(type='v_PostGIS'):
        conn = get_db_connection(store)
        cursor = conn.cursor()
        cursor.execute(definition)
        conn.close()

def insert_def(apps, schema_editor):
    try:
        from django.utils.translation import ugettext_noop as _
        TriggerProcedure = apps.get_model("gvsigol_services", "TriggerProcedure")
        procedure = TriggerProcedure()
        procedure.signature = TRIGGER_SIGNATURE
        procedure.func_name = INVERSE_GEOCODER_CARTOCIUDAD_FUNCTION_NAME
        procedure.func_schema = INVERSE_GEOCODER_CARTOCIUDAD_FUNCTION_SCHEMA
        procedure.label = _('Inverse Geocoder Cartociudad')
        procedure.definition_tpl = InverseGeocoderCartociudad().get_definition()
        procedure.activation = 'BEFORE'
        procedure.event = 'INSERT OR UPDATE'
        procedure.orientation = 'ROW'
        procedure.save()
        
        install_procedure(apps, procedure.definition_tpl)

    except Exception as error:
        print(error)

def remove_def(apps, schema_editor):
    try:
        drop_procedure(INVERSE_GEOCODER_CARTOCIUDAD_FUNCTION_SIGNATURE)
        TriggerProcedure = apps.get_model("gvsigol_services", "TriggerProcedure")
        TriggerProcedure.objects.filter(signature=INVERSE_GEOCODER_CARTOCIUDAD_FUNCTION_SIGNATURE).delete()
    except Exception as error:
        print(error)
        
class Migration(migrations.Migration):
    dependencies = [
        ('gvsigol_services', '0038_auto_20201021_1305'),
    ]

    operations = [
        migrations.RunPython(insert_def, reverse_code=remove_def),
    ]
