# Generated by Django 2.2.27 on 2022-03-28 14:41

from django.db import migrations

def toc_order_fix(apps, schema_editor):
    """
    Ensures base layers have the lowest z-index in toc-order
    """
    from gvsigol_core.utils import get_json_toc
    Project = apps.get_model("gvsigol_core", "Project")
    ProjectLayerGroup = apps.get_model("gvsigol_core", "ProjectLayerGroup")
    for project in Project.objects.all():
        assigned_layergroups = list(ProjectLayerGroup.objects.filter(project=project).values_list("layer_group__id", flat=True))
        try:
            plg = ProjectLayerGroup.objects.get(project=project, baselayer_group=True)
            selected_base_group = plg.layer_group.id
        except:
            selected_base_group = None
        project.toc_order = get_json_toc(assigned_layergroups, selected_base_group)
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0043_projectusergrouprole'),
    ]

    operations = [
        migrations.RunPython(toc_order_fix, reverse_code=migrations.RunPython.noop),
    ]
