# Generated by Django 2.2.28 on 2025-09-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0049_project_viewer_default_crs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='viewer_preferred_ui',
            field=models.TextField(blank=True, choices=[('react_spa_ui', 'Actual (React)'), ('bootstrap_ui', 'Classic - (Bootstrap)')], default=''),
        ),
    ]
