# Generated by Django 2.2.28 on 2025-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0050_project_viewer_preferred_ui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='viewer_preferred_ui',
            field=models.TextField(blank=True, choices=[('react_spa_ui', 'Current (React)'), ('bootstrap_ui', 'Classic (Bootstrap)')], default=''),
        ),
    ]
