# Generated by Django 2.2.28 on 2026-03-09 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gvsigol_core', '0051_update_viewer_preferred_ui_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHomeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('alpha', 'Alphabetical'), ('manual', 'Manual')], default='alpha', max_length=10)),
                ('order_data', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
