# Generated by Django 2.2.28 on 2026-03-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0051_update_viewer_preferred_ui_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('order', models.IntegerField(default=0)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.Application')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.Project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='applicationorder',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('application__isnull', False), ('project__isnull', True)), models.Q(('application__isnull', True), ('project__isnull', False)), _connector='OR'), name='applicationorder_one_of_application_or_project'),
        ),
    ]
