# Generated by Django 2.2.28 on 2026-03-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0052_userhomeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhomeorder',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
