# Generated by Django 2.2.28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_home_order(apps, schema_editor):
    UserHomeOrder = apps.get_model('gvsigol_core', 'UserHomeOrder')
    if not UserHomeOrder.objects.filter(user__isnull=True).exists():
        UserHomeOrder.objects.create(user=None, order_type='alpha', order_data='[]')


def remove_default_home_order(apps, schema_editor):
    UserHomeOrder = apps.get_model('gvsigol_core', 'UserHomeOrder')
    UserHomeOrder.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gvsigol_core', '0053_userhomeorder_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhomeorder',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='home_order',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Only one row with user_id IS NULL (default order). Django 2.2 UniqueConstraint needs fields;
        # partial unique index in SQL enforces this.
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX unique_default_userhomeorder ON gvsigol_core_userhomeorder ((1)) WHERE user_id IS NULL;',
            reverse_sql='DROP INDEX IF EXISTS unique_default_userhomeorder;',
        ),
        migrations.RemoveField(
            model_name='userhomeorder',
            name='is_global',
        ),
        migrations.RunPython(create_default_home_order, remove_default_home_order),
    ]
