# Generated by Django 2.2.28 on 2023-10-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0061_auto_20230914_1227'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='layergrouprole',
            constraint=models.UniqueConstraint(fields=('layergroup', 'permission', 'role'), name='unique_permission_role_per_layergroup'),
        ),
    ]
