# Generated by Django 2.2.28 on 2024-11-22 10:27

try:
    from django.db.models import JSONField
except ImportError:
    from django_jsonfield_backport.models import JSONField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0069_auto_20241122_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerreadrole',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layerreadrole',
            name='filtered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layerwriterole',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layerwriterole',
            name='filtered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='authz_service_conf',
            field=JSONField(default=None, null=True),
        ),
    ]
