# Generated by Django 2.2.28 on 2025-09-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0077_wmts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumeration',
            name='show_first_value',
            field=models.BooleanField(default=False),
        ),
    ]
