# Generated by Django 2.2.28 on 2025-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0081_make_project_not_null'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('title', 'project'), name='unique_category_title_per_project'),
        ),
    ]

