# Generated by Django 2.2.28 on 2026-01-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0083_wmts_options_bis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('PostgreSQL', 'PostgreSQL'), ('PostGIS', 'PostGIS'), ('Oracle', 'Oracle'), ('SQLServer', 'SQL Server'), ('MySQL', 'MySQL'), ('REST_API', 'REST API')], default='PostGIS', max_length=50)),
                ('connection_params', models.TextField(help_text='JSON with connection parameters (encrypted)')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('shared', 'Shared by roles')], default='private', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connections',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='datastore',
            name='legacy_mode',
            field=models.BooleanField(default=True, help_text='True if using connection_params directly, False if using Connection reference'),
        ),
        migrations.AddField(
            model_name='datastore',
            name='schema',
            field=models.CharField(blank=True, help_text='Database schema for this datastore', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='connection_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConnectionRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('permission', models.CharField(choices=[('allow_datastore', 'Allow use in datastores'), ('allow_etl', 'Allow use in ETL'), ('allow_both', 'Allow both')], default='allow_both', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='gvsigol_services.Connection')),
            ],
            options={
                'verbose_name': 'Connection Role',
                'verbose_name_plural': 'Connection Roles',
            },
        ),
        migrations.AddField(
            model_name='datastore',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Reference to centralized connection', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datastores', to='gvsigol_services.Connection'),
        ),
        migrations.AddIndex(
            model_name='connectionrole',
            index=models.Index(fields=['connection', 'role'], name='gvsigol_ser_connect_a2b8c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectionrole',
            constraint=models.UniqueConstraint(fields=('connection', 'role'), name='unique_role_per_connection'),
        ),
    ]
