# Generated by Django 2.2.28 on 2026-01-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0084_auto_20260121_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='extra_params',
            field=models.TextField(blank=True, help_text='Optional additional parameters in JSON format', null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_params',
            field=models.TextField(help_text='JSON with connection parameters'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.CharField(choices=[('PostGIS', 'PostGIS'), ('Oracle', 'Oracle'), ('SQLServer', 'SQL Server'), ('MySQL', 'MySQL'), ('REST_API', 'REST API')], default='PostGIS', max_length=50),
        ),
    ]
