# Generated by Django 2.2.28 on 2026-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0085_auto_20260121_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='connectionrole',
            name='permission',
        ),
        migrations.AddField(
            model_name='connection',
            name='allow_all_datastore',
            field=models.BooleanField(default=False, help_text='Allow all users to create datastores with this connection'),
        ),
        migrations.AddField(
            model_name='connection',
            name='allow_all_etl',
            field=models.BooleanField(default=False, help_text='Allow all users to use this connection in ETL'),
        ),
        migrations.AddField(
            model_name='connection',
            name='allow_all_manage',
            field=models.BooleanField(default=False, help_text='Allow all users to manage this connection (edit, delete)'),
        ),
        migrations.AddField(
            model_name='connectionrole',
            name='can_manage',
            field=models.BooleanField(default=False, help_text='This role can manage this connection (edit, delete)'),
        ),
        migrations.AddField(
            model_name='connectionrole',
            name='can_use_datastore',
            field=models.BooleanField(default=False, help_text='This role can create datastores with this connection'),
        ),
        migrations.AddField(
            model_name='connectionrole',
            name='can_use_etl',
            field=models.BooleanField(default=False, help_text='This role can use this connection in ETL'),
        ),
    ]
