# Generated by Django 2.2.28 on 2026-01-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0089_auto_20260130_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.CharField(choices=[('PostGIS', 'PostgreSQL/PostGIS'), ('Oracle', 'Oracle'), ('SQLServer', 'SQL Server'), ('indenova', 'InDenova'), ('segex', 'SEGEX'), ('sharepoint', 'SharePoint'), ('padron-atm', 'Padrón ATM')], default='PostGIS', max_length=50),
        ),
    ]
