# Generated by Django 2.2.28 on 2026-02-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0090_auto_20260130_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this trigger', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Description of what this trigger does', null=True)),
                ('event', models.CharField(help_text='Events that activate this trigger (comma-separated)', max_length=30)),
                ('timing', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], default='AFTER', help_text='When the trigger executes relative to the event', max_length=10)),
                ('sql_code', models.TextField(help_text='SQL code to execute. Use NEW for inserted/updated row, OLD for deleted/updated row.')),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, the trigger will not be executed')),
                ('scope', models.CharField(choices=[('global', 'Global (all schemas)'), ('schemas', 'Specific schemas')], default='global', help_text='Whether the trigger applies to all schemas or specific ones', max_length=10)),
                ('schemas', models.TextField(blank=True, help_text='JSON array of schema names if scope is "schemas"', null=True)),
                ('is_calculated_field', models.BooleanField(default=False, help_text='If enabled, this trigger can be used as a calculated field in layers')),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(help_text='Connection where this trigger will be executed', limit_choices_to={'type': 'PostGIS'}, on_delete=django.db.models.deletion.CASCADE, related_name='connection_triggers', to='gvsigol_services.Connection')),
            ],
            options={
                'verbose_name': 'Connection Trigger',
                'verbose_name_plural': 'Connection Triggers',
                'ordering': ['connection', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LayerConnectionTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_installed', models.BooleanField(default=False, help_text='Whether the trigger is currently installed in the database')),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_connection_triggers', to='gvsigol_services.Layer')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_connection_triggers', to='gvsigol_services.ConnectionTrigger')),
            ],
            options={
                'verbose_name': 'Layer Connection Trigger',
                'verbose_name_plural': 'Layer Connection Triggers',
            },
        ),
        migrations.AddConstraint(
            model_name='layerconnectiontrigger',
            constraint=models.UniqueConstraint(fields=('layer', 'trigger'), name='unique_conn_trigger_per_layer'),
        ),
        migrations.AddConstraint(
            model_name='connectiontrigger',
            constraint=models.UniqueConstraint(fields=('connection', 'name'), name='unique_conn_trigger_name_per_connection'),
        ),
    ]
