# Generated by Django 2.2.28 on 2026-02-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0091_auto_20260204_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiontrigger',
            name='event',
            field=models.CharField(help_text='Events that activate this trigger (comma-separated: INSERT,UPDATE,DELETE)', max_length=30),
        ),
    ]
