# Generated by Django 2.2.28 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0098_connectiontrigger_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerconnectiontrigger',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Whether the trigger is enabled (active) or disabled in the database'),
        ),
    ]

