# Generated by Django 2.2.28 on 2026-02-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0099_layerconnectiontrigger_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatastoreRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('can_use', models.BooleanField(default=True, help_text='Can use this datastore to create layers')),
                ('can_manage', models.BooleanField(default=False, help_text='Can manage (edit description) this datastore')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Datastore Role',
                'verbose_name_plural': 'Datastore Roles',
            },
        ),
        migrations.RemoveIndex(
            model_name='connectiontriggerrole',
            name='gvsigol_ser_trigger_abc123_idx',
        ),
        migrations.AddField(
            model_name='datastore',
            name='allow_all',
            field=models.BooleanField(default=False, help_text='If enabled, all staff users can use this datastore'),
        ),
        migrations.AddIndex(
            model_name='connectiontriggerrole',
            index=models.Index(fields=['trigger', 'role'], name='gvsigol_ser_trigger_65821f_idx'),
        ),
        migrations.AddField(
            model_name='datastorerole',
            name='datastore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastore_roles', to='gvsigol_services.Datastore'),
        ),
        migrations.AddIndex(
            model_name='datastorerole',
            index=models.Index(fields=['datastore', 'role'], name='gvsigol_ser_datasto_d4fbf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='datastorerole',
            constraint=models.UniqueConstraint(fields=('datastore', 'role'), name='unique_role_per_datastore'),
        ),
    ]
