# Generated by Django 2.2.28 on 2026-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0101_datastore_allow_all_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='annotations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
