# Generated by Django 2.2.28 on 2026-05-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0054_userhomeorder_user_null_default'),
        ('gvsigol_services', '0103_remove_layer_annotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('other_title', models.CharField(blank=True, max_length=150, null=True)),
                ('other_text', models.TextField(blank=True, null=True)),
                ('logo_internal_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('logo_public_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('kind', models.CharField(choices=[('generic', 'Generic'), ('project_specific', 'Project specific')], default='generic', max_length=20)),
                ('apply_to_all_projects', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('copyright_notice', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('contact_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=200, null=True)),
                ('legal_notice', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributions_configs', to='gvsigol_core.Project')),
            ],
            options={
                'verbose_name': 'Attributions config',
                'verbose_name_plural': 'Attributions configs',
            },
        ),
        migrations.CreateModel(
            name='AttributionProjectMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='gvsigol_services.AttributionConfig')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions_memberships', to='gvsigol_core.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AttributionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='gvsigol_services.AttributionConfig')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttributionAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_path', models.CharField(max_length=1024)),
                ('public_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gvsigol_services.AttributionConfig')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='attributionprojectmembership',
            index=models.Index(fields=['project'], name='gvsigol_ser_project_98f033_idx'),
        ),
        migrations.AddConstraint(
            model_name='attributionprojectmembership',
            constraint=models.UniqueConstraint(fields=('config', 'project'), name='unique_attributions_membership_config_project'),
        ),
        migrations.AddIndex(
            model_name='attributionconfig',
            index=models.Index(fields=['kind', 'is_active'], name='gvsigol_ser_kind_d6e1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='attributionconfig',
            index=models.Index(fields=['project'], name='gvsigol_ser_project_54cc70_idx'),
        ),
        migrations.AddConstraint(
            model_name='attributionconfig',
            constraint=models.UniqueConstraint(condition=models.Q(kind='project_specific'), fields=('project',), name='unique_attributions_per_project_when_specific'),
        ),
    ]
