# Generated by Django 2.2.28 on 2026-05-08

try:
    from django.db.models import JSONField
except ImportError:
    from django_jsonfield_backport.models import JSONField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0104_auto_20260508_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributionconfig',
            name='modal_section_order',
            field=JSONField(blank=True, default=list),
        ),
    ]
