# Generated by Django 2.2.28 on 2026-06-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0105_attributionconfig_modal_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.CharField(choices=[('PostGIS', 'PostgreSQL/PostGIS'), ('Oracle', 'Oracle'), ('SQLServer', 'SQL Server'), ('indenova', 'InDenova'), ('segex', 'SEGEX'), ('sharepoint', 'SharePoint'), ('padron-atm', 'Padrón ATM'), ('sgarexws', 'SgaRexWS')], default='PostGIS', max_length=50),
        ),
    ]
