# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gvsigol_services', '0001_initial'),
        ('gvsigol_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlayergroup',
            name='layer_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.LayerGroup'),
        ),
        migrations.AddField(
            model_name='projectlayergroup',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.Project'),
        ),
        migrations.AddField(
            model_name='baselayerproject',
            name='baselayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.BaseLayer'),
        ),
        migrations.AddField(
            model_name='baselayerproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.Project'),
        ),
    ]
