# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-10 09:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0004_auto_20171103_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
