# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-17 11:28


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0007_project_toc_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlayergroup',
            name='layer_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.LayerGroup'),
        ),
    ]
