# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-27 16:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlayergroup',
            name='baselayer_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectlayergroup',
            name='multiselect',
            field=models.BooleanField(default=True),
        ),
    ]
