# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-03 10:34
from __future__ import unicode_literals

from django.db import migrations
        
def configure_projects(apps, schema_editor):
    try:
        Project = apps.get_model("gvsigol_core", "Project")
        ProjectLayerGroup = apps.get_model("gvsigol_core", "ProjectLayerGroup")
        Layer = apps.get_model("gvsigol_services", "Layer")
        LayerGroup = apps.get_model("gvsigol_services", "LayerGroup")
        
        default_baselayergroup = LayerGroup.objects.get(name__exact='__default_baselayergroup__')
        
        default_baselayer = None
        layers = Layer.objects.filter(external=True).filter(type='OSM')
        if len(layers) > 0:
            default_baselayer = layers[0]
        else:
            default_baselayer = Layer(
                name = 'default_external_osm',
                external = True,
                title = 'OpenStreetMap',
                layer_group = default_baselayergroup,
                type = 'OSM',
                visible = False,
                queryable = False,
                cached = False,
                single_image = False,
                time_enabled = False,
                created_by = 'From migration'
            )
            default_baselayer.save()
            
        
        for p in Project.objects.all():
            default_project_baselayergroup = ProjectLayerGroup(
                project = p,
                layer_group = default_baselayergroup,
                multiselect = True,
                baselayer_group = True,
                default_baselayer = default_baselayer.id
            )
            default_project_baselayergroup.save()
            
    except Exception as error:
        print error

class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0021_baselayer_to_externallayer'),
        ('gvsigol_core', '0013_projectlayergroup_default_baselayer'),
    ]

    operations = [
        migrations.RunPython(configure_projects, reverse_code=migrations.RunPython.noop),
    ]
