# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-26 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0019_golsettings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='golsettings',
            unique_together=set([('plugin_name', 'key')]),
        ),
    ]
