# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-02-26 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0033_auto_20210202_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='labels',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
