# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-20 14:47


from django.db import migrations
import ast, json
        
class Migration(migrations.Migration):
    dependencies = [
        ('gvsigol_core', '0034_project_labels'),
    ]

    operations = [
    ]
