# Generated by Django 2.2.19 on 2021-03-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0035_default_empty_imagefields'),
    ]

    operations = [
    ]
