# Generated by Django 2.2.27 on 2022-03-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0039_auto_20220302_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
