# Generated by Django 2.2.27 on 2022-03-28 14:41

from django.db import migrations

def groups_to_roles(apps, schema_editor):
    ProjectUserGroup = apps.get_model("gvsigol_core", "ProjectUserGroup")
    ProjectRole = apps.get_model("gvsigol_core", "ProjectRole")
    for prj_ug in ProjectUserGroup.objects.all():
        try:
            if prj_ug.user_group:
                project_role = ProjectRole()
                project_role.project = prj_ug.project
                project_role.role = prj_ug.user_group.name
                project_role.save()
        except Exception as e:
            print(str(e))


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_auth', '0005_groups_to_roles'),
        ('gvsigol_core', '0042_projectrole'),
    ]

    operations = [
        migrations.RunPython(groups_to_roles, reverse_code=migrations.RunPython.noop),
    ]
