# Generated by Django 2.2.28 on 2024-01-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0047_auto_20230824_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_overview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='layer_overview',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
