# Generated by Django 4.2.30 on 2026-05-22 10:49

from django.db import migrations, models
import uuid

try:
    from django.db.models import JSONField
except ImportError:
    from django_jsonfield_backport.models import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0054_userhomeorder_user_null_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPackageActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('import', 'import'), ('export', 'export')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('partial', 'partial'), ('failed', 'failed')], default='ok', max_length=16)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('import_job_id', models.UUIDField(blank=True, null=True)),
                ('summary_json', JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'gvsigol_project_package_projectpackageactivitylog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPackageExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('zip_filename', models.CharField(blank=True, max_length=512)),
                ('zip_path', models.CharField(blank=True, max_length=1024)),
                ('export_options_json', JSONField(blank=True, default=dict)),
                ('summary_json', JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'gvsigol_project_package_projectpackageexportjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPackageImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('preflight_ok', 'preflight_ok'), ('running', 'running'), ('committed', 'committed'), ('failed', 'failed')], default='draft', max_length=32)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_path', models.CharField(help_text='Absolute or MEDIA-relative path', max_length=1024)),
                ('extract_dir', models.CharField(blank=True, max_length=1024, null=True)),
                ('manifest_json', JSONField(blank=True, null=True)),
                ('wizard_json', JSONField(blank=True, default=dict)),
                ('report_json', JSONField(blank=True, default=list)),
                ('id_map_json', JSONField(blank=True, default=dict)),
                ('result_project_id', models.IntegerField(blank=True, null=True)),
                ('summary_json', JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'gvsigol_project_package_projectpackageimportjob',
                'ordering': ['-created_at'],
            },
        ),
    ]
