# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-02 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0020_auto_20191126_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedview',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
