organismo=Direcció General de Costes, Ports i Aeroports
leyenda=Leyenda
titulo_del_plano=Título del plano
sistema_de_referencia_de_coordenadas=Sistema de referencia de coordenadas
fecha=Fecha
escala=Escala
plano_detalle_original_a4=(Plano detalle, original A4)
locale=es-es
