organismo=Direcció General de Costes, Ports i Aeroports
leyenda=Llegenda
titulo_del_plano=Títol del plànol
sistema_de_referencia_de_coordenadas=Sistema de referència de coordenades
fecha=Data
escala=Escala
plano_detalle_original_a4=(Plànol detall, original A4)
locale=ca-es
