# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-10 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0003_auto_20170807_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='temporary',
            new_name='time_enabled',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='temporary_endfield',
            new_name='time_enabled_endfield',
        ),
        migrations.RenameField(
            model_name='layer',
            old_name='temporary_field',
            new_name='time_enabled_field',
        ),
    ]
