# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0022_layer_allow_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='detailed_info_button_title',
            field=models.CharField(blank=True, default='Detailed info', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='detailed_info_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='detailed_info_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
