# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-02-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0047_layer_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='real_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='update_interval',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
