organismo=Dirección General de Infraestructuras de Transporte Terrestre
colFecha=Fecha
colHora=Hora
colCarretera=Carretera
colPKInicial=PK Inicial
colPKFinal=PK Final
colDescripcion=Descripción
colTipo=Tipo
colEstado=Estado
colTitular=Titular
colComarcaInicial=Comarca Inicial
colComarcaFinal=Comarca Final
colEquivalencia=Equivalencia DGT

condicionada=CONDICIONADA
incidencias=INCIDENCIAS
problemasGenerales=PROBLEMAS GENERALES
cadenas=CADENAS
cerrada=CERRADA
calzada_viable_con_posible_evolucion_negativa=Calzada viable con posible evolución negativa
calzada_con_diversos_problemas_que_la_hacen_compleja_y_prohibicion_de_circular_vehiculos_pesados_y_articulados=Calzada con diversos problemas que la hacen compleja y prohibición de circular vehículos pesados y articulados.
tramos_danyados_y_o_viabilidad_parcial=Tramos dañados y/o viabilidad parcial.
con_nieve_circulacion_con_cadenas_y_prohibicion_de_circulacion_de_vehiculos_pesados_y_articulados=Con nieve, circulación con cadenas y prohibición de circulación de vehículos pesados y articulados.
imposibilidad_de_circular=Imposibilidad de circular.
verde=Verde
amarillo=Amarillo
rojo=Rojo
negro=Negro
la_informacion_que_se_publica_es_la_facilitada_por_los_titulares_de_las_carreteras_o_en_su_caso_por_la_autoridad_de_transito=La información que se publica es la facilitada por los titulares de las carreteras o, en su caso, por la autoridad de tránsito
registros_marcados_son_aquellos_que_han_variado_desde_el_anterior_informe_emitido=Registros marcados con aquellos que han variado desde el anterior informe emitido
descripcion_de_los_estados_de_las_vias=Descripción de los estados de las vías
