organismo=Direcció General d'infraestructures viàries
colFecha=Data
colHora=Hora
colCarretera=Carretera
colPKInicial=PK Inicial
colPKFinal=PK Final
colDescripcion=Descripció
colTipo=Tipus
colEstado=Estat
colTitular=Titular
colComarcaInicial=Comarca Inicial
colComarcaFinal=Comarca Final
colEquivalencia=Equivalència DGT

condicionada=CONDICIONADA
incidencias=INCIDÈNCIES
problemasGenerales=PROBLEMES GENERAL
cadenas=CADENES
cerrada=TANCADA (CERRADA)
calzada_viable_con_posible_evolucion_negativa=Calçada viable amb possible evolució negativa.
calzada_con_diversos_problemas_que_la_hacen_compleja_y_prohibicion_de_circular_vehiculos_pesados_y_articulados=Calçada amb diversos problemes de vialitat complicada. Amb neu, prohibició de circular vehicles pesats i articulats.
tramos_danyados_y_o_viabilidad_parcial=Trams danyats i/o de vialitat parcial.
con_nieve_circulacion_con_cadenas_y_prohibicion_de_circulacion_de_vehiculos_pesados_y_articulados=Amb neu, circulació amb cadenes i prohibició de circulació de vehicles pesats i articulats.
imposibilidad_de_circular=Impossibilitat de circular.
verde=Verd (Verde)
amarillo=Groc (Amarillo)
rojo=Roig (Rojo)
negro=Negre (Negro)
la_informacion_que_se_publica_es_la_facilitada_por_los_titulares_de_las_carreteras_o_en_su_caso_por_la_autoridad_de_transito=La informació que es publica és la facilitada pels titulars de les carreteres o, en el seu cas, per l'autoritat de trànsit
registros_marcados_son_aquellos_que_han_variado_desde_el_anterior_informe_emitido=Registres marcats son aquells que han variat desde l'anterior informe emés
descripcion_de_los_estados_de_las_vias=Descripció dels estats viaris
