# Generated by Django 2.2.28 on 2025-10-31 07:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gvsigol_core', '0051_update_viewer_preferred_ui_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleDownloadConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_configs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Configuración de archivos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.Project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Configuración Simple Download',
                'verbose_name_plural': 'Configuraciones Simple Download',
            },
        ),
    ]
