# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-01 11:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0006_auto_20190924_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadlink',
            old_name='request_random_id',
            new_name='link_random_id',
        ),
        migrations.RenameField(
            model_name='downloadrequest',
            old_name='retry_count',
            new_name='notify_retry_count',
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='package_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
