# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-01 17:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0007_auto_20191001_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='notification_status',
            field=models.CharField(choices=[('NC', 'Notification completed'), ('NE', 'Notification error'), ('NP', 'Permanent notification error')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='request_status',
            field=models.CharField(choices=[('AU', 'Pending authorization'), ('QP', 'Package queued'), ('CT', 'Packaged'), ('CT', 'Completed'), ('RE', 'Rejected'), ('HO', 'On hold'), ('CL', 'Cancelled'), ('ER', 'Packaging error'), ('PE', 'Permanent packaging error')], max_length=2),
        ),
    ]
