# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gvsigol_core', '0008_auto_20171117_1128'),
        ('gvsigol_services', '0009_auto_20171002_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('srs', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Layer')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_survey.Survey')),
            ],
        ),
    ]
