# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0004_auto_20170810_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='time_default_value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_default_value_mode',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_presentation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_resolution',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
