# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-02 11:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0008_layergroup_toc_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layergroup',
            name='toc_order',
        ),
        migrations.AddField(
            model_name='layer',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
