# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0009_auto_20171002_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='time_mosaic_date_regex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_mosaic_elev_regex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='time_resolution',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
