# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0013_workspace_wmts_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='frontend_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
