# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-17 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0016_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='layergroup',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Workspace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layer',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/gvsigonline/static/img/no_thumbnail.jpg', null=True, upload_to='thumbnails'),
        ),
    ]
