# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-06 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import gvsigol_services.models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0017_workspace_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layergroup',
            name='workspace_id',
        ),
        migrations.AddField(
            model_name='layergroup',
            name='server_id',
            field=models.IntegerField(default=gvsigol_services.models.get_default_server, null=True),
        ),
    ]
