# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-05 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0024_layerfieldenumeration'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerfieldenumeration',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
    ]
