# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-20 12:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0030_remove_layer_default_srs'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='latlong_extent',
            field=models.CharField(default='-180,-90,180,90', max_length=250),
        ),
        migrations.AddField(
            model_name='layer',
            name='native_extent',
            field=models.CharField(default='-180,-90,180,90', max_length=250),
        ),
        migrations.AddField(
            model_name='layer',
            name='native_srs',
            field=models.CharField(default='EPSG:4326', max_length=100),
        ),
    ]
