# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-31 18:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0035_auto_20200727_1638'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='layerresource',
            index=models.Index(fields=['layer', 'feature'], name='gvsigol_ser_layer_i_93190e_idx'),
        ),
        migrations.AddIndex(
            model_name='layerresource',
            index=models.Index(fields=['path'], name='gvsigol_ser_path_ef84d0_idx'),
        ),
    ]
