# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2021-02-22 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0048_auto_20210222_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='update_interval',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
