# Generated by Django 2.2.28 on 2023-09-13 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0059_auto_20230720_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerManageRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='LayerGroupManageRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('layergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.LayerGroup')),
            ],
        ),
        migrations.AddIndex(
            model_name='layermanagerole',
            index=models.Index(fields=['layer', 'role'], name='gvsigol_ser_layer_i_1beba5_idx'),
        ),
        migrations.AddConstraint(
            model_name='layermanagerole',
            constraint=models.UniqueConstraint(fields=('layer', 'role'), name='unique_manage_role_per_layer'),
        ),
        migrations.AddIndex(
            model_name='layergroupmanagerole',
            index=models.Index(fields=['layergroup', 'role'], name='gvsigol_ser_layergr_eb9a80_idx'),
        ),
    ]
