# Generated by Django 2.2.28 on 2024-04-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0065_fix_duplicate_layer_roles'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='layerreadrole',
            constraint=models.UniqueConstraint(fields=('layer', 'role'), name='unique_read_role_per_layer'),
        ),
        migrations.AddConstraint(
            model_name='layerwriterole',
            constraint=models.UniqueConstraint(fields=('layer', 'role'), name='unique_write_role_per_layer'),
        ),
    ]
