# Generated by Django 2.2.28 on 2025-05-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0070_auto_20241122_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProj', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('position_lat', models.FloatField()),
                ('position_lng', models.FloatField()),
                ('zoom', models.FloatField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
