# Generated by Django 2.2.28 on 2025-08-04 14:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0049_project_viewer_default_crs'),
        ('gvsigol_services', '0074_layertopologyconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layertopologyconfiguration',
            name='covered_by_layer',
            field=models.CharField(blank=True, help_text='Capa que debe cubrir en formato schema.tabla', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layertopologyconfiguration',
            name='overlap_layers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Lista de capas con las que no debe solapar en formato schema.tabla'),
        ),
        migrations.CreateModel(
            name='FavoriteFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('share_filter', models.BooleanField(default=False)),
                ('filter_data', django.contrib.postgres.fields.jsonb.JSONField(help_text='Estructura JSON con la configuración del filtro')),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Layer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.Project')),
            ],
            options={
                'verbose_name': 'Favorite Filter',
                'verbose_name_plural': 'Favorite Filters',
            },
        ),
        migrations.AddIndex(
            model_name='favoritefilter',
            index=models.Index(fields=['project', 'layer'], name='gvsigol_ser_project_0e4bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritefilter',
            index=models.Index(fields=['created_by'], name='gvsigol_ser_created_24ff52_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritefilter',
            index=models.Index(fields=['share_filter'], name='gvsigol_ser_share_f_9dd8d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoritefilter',
            constraint=models.UniqueConstraint(fields=('name', 'project', 'layer', 'created_by'), name='unique_favorite_filter_per_user_layer'),
        ),
    ]
