# Generated by Django 2.2.28 on 2025-10-01 11:46

from django.db import migrations, models
import django.db.models.deletion


def check_no_null_projects(apps, schema_editor):
    """
    Verifica que no queden categorías con project_id NULL antes de hacer el campo NOT NULL.
    """
    Category = apps.get_model('gvsigol_services', 'Category')
    
    null_count = Category.objects.filter(project__isnull=True).count()
    
    if null_count > 0:
        raise Exception(f"CRÍTICO: Quedan {null_count} categorías con project_id NULL. "
                       f"No se puede hacer el campo NOT NULL. "
                       f"Revisa la migración anterior.")


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0080_populate_project_data'),
    ]

    operations = [
        migrations.RunPython(check_no_null_projects, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='gvsigol_core.Project'),
        ),
    ]
