# Generated by Django 2.2.28 on 2026-02-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0093_layerconnectiontrigger_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectiontrigger',
            name='is_active',
        ),
    ]



