# Generated by Django 2.2.28 on 2026-02-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0094_remove_connectiontrigger_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiontrigger',
            name='allow_all',
            field=models.BooleanField(default=False, help_text='Allow all staff users to use this trigger in their layers'),
        ),
        migrations.CreateModel(
            name='ConnectionTriggerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_roles', to='gvsigol_services.ConnectionTrigger')),
            ],
            options={
                'indexes': [models.Index(fields=['trigger', 'role'], name='gvsigol_ser_trigger_abc123_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='connectiontriggerrole',
            constraint=models.UniqueConstraint(fields=('trigger', 'role'), name='unique_role_per_trigger'),
        ),
    ]



