# Generated by Django 2.2.28 on 2026-02-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0100_auto_20260217_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='allow_all_manage',
            field=models.BooleanField(default=False, help_text='If enabled, all staff users can manage (edit) this datastore'),
        ),
    ]
