# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-12 10:52


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_survey', '0004_survey_datastore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='datastore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Datastore'),
        ),
    ]
