# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-15 09:37


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_survey', '0006_survey_layer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gvsigol_core.Project'),
        ),
        migrations.AlterField(
            model_name='surveysection',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gvsigol_services.Layer'),
        ),
    ]
