# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gvsigol_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idField', models.CharField(max_length=100)),
                ('textField', models.CharField(blank=True, max_length=100, null=True)),
                ('typeField', models.CharField(blank=True, max_length=100, null=True)),
                ('geomField', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update', models.DateTimeField()),
                ('image', models.ImageField(blank=True, default='/gvsigonline/static/img/geocoding/toponimos.png', null=True, upload_to='images')),
                ('order', models.IntegerField(default=0)),
                ('dataStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Datastore')),
            ],
        ),
    ]
