# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geocoding', '0004_auto_20170213_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
