# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-22 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geocoding', '0007_auto_20170222_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='resource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
