templates:
  #===========================================================================
  Caminos agricolas: !template
  #===========================================================================
    reportTemplate: a3_landscape.jrxml
    attributes:
      title: !string
        default: "Default Title"
      USER_DATE_fecha: !string
        default: ""
      USER_numPlano: !string
        default: "#/#"
      crs: !string
        default: "EPSG:3857"
      crsPermanent: !string
        default: "EPSG:3857"
      legalWarning: !string
        default: "Legal Warning"
      map: !map
        maxDpi: 400
        width: 1150
        height: 718
        default:
          useAdjustBounds: true
      scalebar: !scalebar
        width: 200
        height: 30
        default:
          backgroundColor: "rgba(255, 255, 255, 0)"
          align: "center"
          fontSize: 8
          barSize: 6
          geodetic: false
          barsize: 250
          linewidth: 1
          subIntervals: true
      northArrowDef: !northArrow
        size: 60
        default:
          graphic: "file://NorthArrow_10.svg"
          backgroundColor: "rgba(255, 255, 255, 0)"
      legend: !legend {}
      logo_url: !string
        default: "logo.png"
      scale: !string
        default: ""
        
    processors:
    # - !configureHttpRequests
    #   httpProcessors:
    #     - !restrictUris
    #       matchers:
    #         - !localMatch {}
    #         - !acceptAll {}
    #     - !forwardHeaders
    #       headers: [Referer, User-Agent]
    #     # Add a static header to all http requests
    #     - !addHeaders
    #       headers:
    #         newHeader : 'headerValue'
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !createNorthArrow
        inputMapper: {map: map, northArrowDef: northArrow}
    - !prepareLegend # create a datasource for the report with the 'legend' attribute
      maxWidth: 16
      dpi: 100
      scaled: true      
      template: legend.jrxml
      inputMapper: {legend: legend}
      outputMapper:
        legendDataSource: legendDataSource
        legendSubReport: legendSubReport
        numberOfLegendRows: numberOfLegendRows
