# Generated by Django 2.2.28 on 2025-11-03 16:16

try:
    from django.db.models import JSONField
except ImportError:
    from django_jsonfield_backport.models import JSONField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_simpledownload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpledownloadconfig',
            name='file_configs',
            field=JSONField(blank=True, default=list, verbose_name='Configuración de archivos'),
        ),
    ]
