# Generated by Django 2.2.28 on 2025-11-03 16:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_simpledownload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpledownloadconfig',
            name='file_configs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Configuración de archivos'),
        ),
    ]
