# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-02-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('params', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='/gvsigonline/static/img/geocoding/toponimo.png', null=True, upload_to='images')),
                ('order', models.IntegerField(default=10)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
