# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geocoding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='geomField',
            new_name='geom_field',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='idField',
            new_name='id_field',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='textField',
            new_name='text_field',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='typeField',
            new_name='type_field',
        ),
    ]
