# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-17 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import gvsigol_plugin_geocoding.models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geocoding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.ImageField(blank=True, default=gvsigol_plugin_geocoding.models.get_default_provider_icon, null=True, upload_to='images'),
        ),
    ]
