# Generated by Django 2.2.28 on 2025-02-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geocoding', '0002_auto_20190517_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logstashetl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150)),
                ('config', models.TextField()),
                ('provider_id', models.IntegerField()),
            ],
        ),
    ]
