# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geocoding', '0002_auto_20170213_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='geom_field',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='last_update',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='text_field',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='type_field',
            field=models.CharField(max_length=100),
        ),
    ]
