# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geocoding', '0003_auto_20170213_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
