# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-22 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geocoding', '0005_auto_20170213_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='table_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.ImageField(blank=True, default='/gvsigonline/static/img/geocoding/toponimo.png', null=True, upload_to='images'),
        ),
    ]
