# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0001_initial'),
        ('gvsigol_plugin_geocoding', '0008_provider_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='dataStore',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='geom_field',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='id_field',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='text_field',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='type_field',
        ),
        migrations.AddField(
            model_name='provider',
            name='datastore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Datastore'),
        ),
        migrations.AddField(
            model_name='provider',
            name='params',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='type',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
