# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-28 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geocoding', '0010_remove_provider_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='datastore',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='resource',
        ),
    ]
