# Generated by Django 2.2.28 on 2023-08-22 11:59

from django.db import migrations
from django.apps import apps as global_apps


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_survey', '0011_usergroups_to_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyreadgroup',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='surveywritegroup',
            name='user_group',
        ),
    ]

    try:
        SurveyReadGroup = global_apps.get_model("gvsigol_plugin_survey", "SurveyReadGroup")
        SurveyWriteGroup = global_apps.get_model("gvsigol_plugin_survey", "SurveyWriteGroup")
        if SurveyReadGroup.objects.all().exists() or SurveyWriteGroup.objects.all().exists():
            # si no es una instalación nueva del plugin, debemos ejecutar estas migraciones antes de borrar projectusergroup
            run_before = [
                ('gvsigol_core', '0046_delete_projectusergroup'),
            ]
    except Exception as e:
        print("Survey está vacío")
        print(e)
