# -*- coding: utf-8 -*-
CATALOG_URL = '##CATALOG_URL##'
CATALOG_BASE_URL = '##CATALOG_BASE_URL##'
CATALOG_USER = '##GEONETWORK_USER##'
CATALOG_PASSWORD = '##GEONETWORK_PASS##'
# valid values: 'legacy3.2', 'api0.1'
CATALOG_API_VERSION = '##CATALOG_API_VERSION##'
