# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-25 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_worldwind', '0002_auto_20190925_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldwindprovider',
            name='type',
            field=models.CharField(choices=[('url', 'Url'), ('mapserver', 'Mapserver')], default='url', max_length=250),
        ),
    ]
