# Generated by Django 2.2.28 on 2023-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_prueba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
