# Generated by Django 2.2.18 on 2021-10-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0004_etlstatus_id_ws'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlworkspaces',
            name='username',
            field=models.CharField(default='carlesmarti', max_length=250),
        ),
    ]
