# Generated by Django 2.2.18 on 2022-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0007_database_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_connections',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
