# Generated by Django 2.2.18 on 2022-07-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0008_auto_20220505_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlworkspaces',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
