# Generated by Django 2.2.18 on 2023-01-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0011_remove_segex_fechafingarantizada_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastral_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cadastral_requests', max_length=20)),
                ('requests', models.IntegerField(default=0)),
                ('lastRequest', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
