# Generated by Django 2.2.28 on 2023-07-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0017_auto_20230627_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlWorkspaceExecuteRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('etl_ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_geoetl.ETLworkspaces')),
            ],
        ),
        migrations.CreateModel(
            name='EtlWorkspaceEditRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('etl_ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_geoetl.ETLworkspaces')),
            ],
        ),
        migrations.AddIndex(
            model_name='etlworkspaceexecuterole',
            index=models.Index(fields=['etl_ws', 'role'], name='gvsigol_plu_etl_ws__23872a_idx'),
        ),
        migrations.AddIndex(
            model_name='etlworkspaceeditrole',
            index=models.Index(fields=['etl_ws', 'role'], name='gvsigol_plu_etl_ws__df891d_idx'),
        ),
    ]
