# Generated by Django 2.2.28 on 2023-11-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0019_auto_20230721_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_after', models.BooleanField(default=False)),
                ('send_fails', models.BooleanField(default=False)),
                ('etl_ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_geoetl.ETLworkspaces')),
            ],
        ),
        migrations.AddIndex(
            model_name='sendemails',
            index=models.Index(fields=['etl_ws'], name='gvsigol_plu_etl_ws__dbc7a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='sendemails',
            constraint=models.UniqueConstraint(fields=('etl_ws',), name='unique_etlws_per_send_row'),
        ),
    ]
