# Generated by Django 2.2.28 on 2024-06-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0023_etlstatus_last_exec'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_after', models.BooleanField(default=False)),
                ('send_fails', models.BooleanField(default=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('etl_ws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_geoetl.ETLworkspaces')),
            ],
        ),
        migrations.AddIndex(
            model_name='sendendpoint',
            index=models.Index(fields=['etl_ws'], name='gvsigol_plu_etl_ws__d9fe91_idx'),
        ),
        migrations.AddConstraint(
            model_name='sendendpoint',
            constraint=models.UniqueConstraint(fields=('etl_ws',), name='unique_etlws_per_endpoint_row'),
        ),
    ]
