# Generated by Django 2.2.28 on 2025-04-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0025_tempetltable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLPluginSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl_hours', models.PositiveIntegerField(default=24, help_text='Tiempo en horas tras el cual las tablas temporales se consideran obsoletas.')),
            ],
            options={
                'verbose_name': 'Configuración del Plugin ETL',
                'verbose_name_plural': 'Configuración del Plugin ETL',
            },
        ),
    ]
