# Generated by Django 2.2.28 on 2025-10-01 12:00

from django.db import migrations


def remove_periodic_cadastral_task(apps, schema_editor):
    """
    Elimina la tarea periódica 'periodic_cadastral_requests' que ya no se necesita
    porque la funcionalidad se ha movido inline en trans_CadastralGeom
    """
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    
    # Eliminar la tarea periódica si existe
    PeriodicTask.objects.filter(
        name='gvsigol_plugin_geoetl.periodic_cadastral_requests'
    ).delete()


def reverse_removal(apps, schema_editor):
    """
    No hacemos nada en el reverse porque la tarea ya no existe en el código
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0026_etlpluginsettings'),
        ('django_celery_beat', '__first__'),  # Asegura que las tablas de celery beat existan
    ]

    operations = [
        migrations.RunPython(remove_periodic_cadastral_task, reverse_removal),
    ] 