# Generated by Django 2.2.28 on 2025-10-20 15:44

from django.db import migrations, models
from django.db.models import Count


def cleanup_duplicate_etlstatus(apps, schema_editor):
    """
    Limpia registros duplicados de ETLstatus antes de aplicar el constraint de unicidad.
    Conserva el registro más reciente (por last_exec) para cada id_ws.
    """
    try:
        ETLstatus = apps.get_model('gvsigol_plugin_geoetl', 'ETLstatus')
        
        # Encontrar id_ws con duplicados
        duplicates = (ETLstatus.objects
                      .filter(id_ws__isnull=False)
                      .values('id_ws')
                      .annotate(count=Count('id'))
                      .filter(count__gt=1))
        
        total_deleted = 0
        
        for dup in duplicates:
            id_ws = dup['id_ws']
            
            # Obtener todos los registros para este id_ws, ordenados por fecha (más reciente primero)
            status_records = ETLstatus.objects.filter(id_ws=id_ws).order_by('-last_exec', '-id')
            
            if status_records.count() > 1:
                # Conservar el primero (más reciente) y eliminar los demás
                keep_id = status_records.first().id
                deleted = status_records.exclude(id=keep_id).delete()[0]
                total_deleted += deleted
                
                print(f"  Workspace ID {id_ws}: Eliminados {deleted} duplicados, conservado ID {keep_id}")
        
        if total_deleted > 0:
            print(f"\n- Limpieza completada: {total_deleted} registros duplicados eliminados")
        else:
            print("- No se encontraron duplicados")
    except:
      import logging
      logging.getLogger('gvsigol').exception("Error en cleanup_duplicate_etlstatus")

def reverse_cleanup(apps, schema_editor):
    """
    No hacemos nada en el reverse - los duplicados eliminados no se pueden recuperar.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0027_remove_periodic_cadastral_requests'),
    ]

    operations = [
        # Primero: Limpiar duplicados
        migrations.RunPython(cleanup_duplicate_etlstatus, reverse_cleanup),
        
        # Segundo: Aplicar el constraint de unicidad
        migrations.AddConstraint(
            model_name='etlstatus',
            constraint=models.UniqueConstraint(condition=models.Q(id_ws__isnull=False), fields=('id_ws',), name='unique_etlstatus_per_workspace'),
        ),
    ]
