# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-17 10:32


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationRequestForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_download', models.FileField(upload_to=b'')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('valid_to', models.DateTimeField(db_index=True)),
                ('request_random_id', models.TextField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.TextField(blank=True, null=True)),
                ('laye_id_type', models.CharField(choices=[('GNUU', 'GEONETWORK_UUID'), ('GVID', 'GVSIGOL_LAYER_ID')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_external', models.CharField(max_length=500)),
                ('requested_by_user', models.CharField(blank=True, max_length=500, null=True)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('validity', models.IntegerField()),
                ('authorization_request', models.TextField()),
                ('pending_authorization', models.BooleanField()),
                ('request_status', models.CharField(choices=[('AU', 'Pending authorization'), ('IN', 'Initial notification pending'), ('FN', 'Final notification pending'), ('QP', 'Package queued'), ('CT', 'Packaged'), ('CT', 'Completed'), ('RE', 'Rejected'), ('HO', 'On hold'), ('CL', 'Cancelled'), ('RE', 'Packaging error'), ('RE', 'Permanent packaging error'), ('RE', 'Notification error'), ('RE', 'Permanent notification error')], max_length=2)),
                ('notification_status', models.CharField(choices=[('RG', 'Registered request notification has been queued')], max_length=2, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('request_random_id', models.TextField(db_index=True)),
                ('json_request', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLocator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_type', models.CharField(choices=[('CT', 'Catalog'), ('GV', 'gvSIGOL Layer'), ('GS', 'Geoserver'), ('FI', 'File Path'), ('FD', 'Folder Path'), ('HT', 'Http Link')], max_length=2)),
                ('data_source', models.TextField()),
                ('layer_id', models.TextField(blank=True, null=True)),
                ('laye_id_type', models.CharField(choices=[('GNUU', 'GEONETWORK_UUID'), ('GVID', 'GVSIGOL_LAYER_ID')], max_length=2)),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_downloadman.DownloadRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_uuid', models.TextField(unique=True)),
                ('restricted', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_downloadman.DownloadRequest'),
        ),
        migrations.AddField(
            model_name='downloadlink',
            name='contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_downloadman.DownloadRequest'),
        ),
    ]
