# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-21 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='laye_id_type',
            field=models.CharField(choices=[('GN', 'GEONETWORK_UUID'), ('GV', 'GVSIGOL_LAYER_ID')], max_length=2),
        ),
        migrations.AlterField(
            model_name='resourcelocator',
            name='laye_id_type',
            field=models.CharField(choices=[('GN', 'GEONETWORK_UUID'), ('GV', 'GVSIGOL_LAYER_ID')], max_length=2),
        ),
    ]
