# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0005_auto_20190924_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='prepared_download_path',
            field=models.FilePathField(),
        ),
    ]
