# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0009_auto_20191003_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='request_status',
            field=models.CharField(choices=[('AU', 'Pending authorization'), ('QP', 'Package queued'), ('PR', 'Processing request'), ('SP', 'Queued, waiting for free space'), ('CT', 'Packaged'), ('CT', 'Completed'), ('RE', 'Rejected'), ('HO', 'On hold'), ('CL', 'Cancelled'), ('ER', 'Packaging error'), ('PE', 'Permanent packaging error')], db_index=True, max_length=2),
        ),
    ]
