# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-24 20:42


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0012_auto_20191115_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.TextField(blank=True, null=True)),
                ('layer_id_type', models.CharField(choices=[('GN', 'GEONET_DATA_SOURCE'), ('GV', 'GVSIGOL_DATA_SOURCE')], max_length=2)),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('title_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LayerResourceProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('fq_name', models.TextField()),
                ('fq_title', models.TextField()),
                ('fq_title_name', models.TextField()),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_downloadman.LayerProxy')),
            ],
        ),
        migrations.RemoveField(
            model_name='downloadlog',
            name='resource',
        ),
        migrations.AddField(
            model_name='downloadlink',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='notification_status',
            field=models.CharField(choices=[('NI', 'Initial notification completed'), ('NC', 'Notification completed'), ('NE', 'Notification error'), ('NP', 'Permanent notification error')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='resourcelocator',
            name='status',
            field=models.CharField(choices=[('AU', 'Pending authorization'), ('QP', 'Package queued'), ('PG', 'Processing resource'), ('SP', 'Queued, waiting for free space'), ('PD', 'Processed'), ('RE', 'Rejected'), ('HO', 'On hold'), ('CL', 'Cancelled'), ('ER', 'Temporal error'), ('PE', 'Permanent error')], db_index=True, default='QP', max_length=2),
        ),
        migrations.DeleteModel(
            name='DownloadLog',
        ),
    ]
