# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-26 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0013_auto_20191124_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='request',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_downloadman.DownloadRequest'),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='status',
            field=models.CharField(choices=[('PR', 'Processed'), ('UC', 'Cancelled by the user'), ('AC', 'Cancelled by the administrator')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='layerproxy',
            name='layer_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcelocator',
            name='request',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_downloadman.DownloadRequest'),
        ),
        migrations.AlterField(
            model_name='resourcelocator',
            name='status',
            field=models.CharField(choices=[('AU', 'Pending authorization'), ('QP', 'Package queued'), ('PG', 'Processing resource'), ('SP', 'Queued, waiting for free space'), ('PD', 'Processed'), ('RE', 'Rejected'), ('HO', 'On hold'), ('CL', 'Cancelled'), ('ER', 'Temporal error'), ('PE', 'Permanent error')], default='QP', max_length=2),
        ),
        migrations.AddIndex(
            model_name='downloadlink',
            index=models.Index(fields=['request', 'valid_to'], name='gvsigol_plu_request_3dc93f_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelocator',
            index=models.Index(fields=['request', 'status', 'pending_authorization'], name='gvsigol_plu_request_54ec8c_idx'),
        ),
        migrations.AddIndex(
            model_name='layerproxy',
            index=models.Index(fields=['layer_id', 'layer_id_type'], name='gvsigol_plu_layer_i_775155_idx'),
        ),
    ]
