# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0014_auto_20191126_1104'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='downloadlink',
            name='gvsigol_plu_request_3dc93f_idx',
        ),
        migrations.RemoveIndex(
            model_name='resourcelocator',
            name='gvsigol_plu_request_54ec8c_idx',
        ),
        migrations.RemoveField(
            model_name='resourcelocator',
            name='pending_authorization',
        ),
        migrations.AddField(
            model_name='resourcelocator',
            name='authorization',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not required'), (1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='resourcelocator',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resourcelocator',
            name='status',
            field=models.CharField(choices=[('QD', 'Resource queued'), ('SP', 'Queued, waiting for free space'), ('PD', 'Processed'), ('HO', 'On hold'), ('TE', 'Temporal error'), ('PE', 'Permanent error')], default='QD', max_length=2),
        ),
        migrations.AddIndex(
            model_name='downloadlink',
            index=models.Index(fields=['request', 'valid_to', 'status'], name='gvsigol_plu_request_17c589_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelocator',
            index=models.Index(fields=['request', 'canceled', 'status', 'authorization'], name='gvsigol_plu_request_02d97b_idx'),
        ),
    ]
