# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-10 00:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0015_auto_20191128_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='authorization_request',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resourcelocator',
            name='authorization',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not processed'), (4, 'Not required'), (1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=0),
        ),
    ]
