# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-10 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0016_auto_20191210_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrequest',
            name='authorization_request',
        ),
    ]
