# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-11 16:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0017_remove_downloadrequest_authorization_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='pending_authorization',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
