# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-11 17:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0018_downloadrequest_pending_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='status',
            field=models.CharField(choices=[('PR', 'Processed #sing#'), ('UC', 'Cancelled by the user'), ('AC', 'Cancelled by the administrator')], default='PR', max_length=2),
        ),
    ]
