# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-10 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0020_auto_20200109_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlink',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
