# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-06 09:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0022_downloadrequest_shared_view_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='generic_request',
            field=models.BooleanField(default=False),
        ),
    ]
