# Generated by Django 2.2.27 on 2022-10-27 11:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    dependencies = [
        ('gvsigol_plugin_featureapi', '0001_initial'),
    ]
    

    operations = [
        # migrations.RunSQL(
        #     "INSERT INTO public.gvsigol_plugin_featureapi_featureversions \
        #     (id, version, wkb_geometry, fields, date, usr, feat_id, operation, resource, layer_id) \
        #     SELECT id, version, wkb_geometry, fields, date, usr, feat_id, operation, resource, layer_id FROM public.gvsigol_plugin_restapi_featurechange"
        # )
    ]
