# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-19 06:45


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0002_auto_20170605_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('type_params', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseLayerProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('baselayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.BaseLayer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_core.Project')),
            ],
        ),
    ]
