# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-17 13:05


from django.db import migrations, models
import gvsigol_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0009_project_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default=gvsigol_core.models.get_default_project_image, null=True, upload_to='images'),
        ),
    ]
