# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-21 08:28


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0010_sharedview'),
        ('gvsigol_core', '0010_auto_20190517_1305'),
    ]

    operations = [
    ]
