# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-13 17:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0017_project_selectable_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='restricted_extent',
            field=models.BooleanField(default=False),
        ),
    ]
