# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-19 08:09


from django.db import migrations
from gvsigol import settings

def update_logo(apps, schema_editor):
    try:
        Project = apps.get_model("gvsigol_core", "Project")
        for p in Project.objects.all():
            p.logo = settings.STATIC_URL + 'img/logo_principal.png'
            p.logo_link = '#'
            p.save()
            
    except Exception as error:
        print(str(error))

class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0024_auto_20200619_0809'),
    ]

    operations = [
        migrations.RunPython(update_logo, reverse_code=migrations.RunPython.noop),
    ]
