# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-30 13:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0027_fix_project_extent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extent4326_minx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extent4326_miny',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extent4326_maxx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='extent4326_maxy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
