# Generated by Django 2.2.20 on 2022-03-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0038_merge_20211123_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonelayers',
            name='layer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Layer'),
        ),
    ]
