# Generated by Django 2.2.27 on 2022-04-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0040_project_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectzone',
            name='pkgassigned',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zonelayers',
            name='pkgassigned',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
