# Generated by Django 2.2.28 on 2023-08-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0046_delete_projectusergroup'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectrole',
            name='gvsigol_cor_project_0d1a20_idx',
        ),
        migrations.AddField(
            model_name='projectrole',
            name='permission',
            field=models.TextField(choices=[('read', 'read'), ('manage', 'manage')], default='read'),
        ),
        migrations.AddIndex(
            model_name='projectrole',
            index=models.Index(fields=['project', 'permission', 'role'], name='gvsigol_cor_project_19db1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.UniqueConstraint(fields=('project', 'permission', 'role'), name='unique_permission_role_and_project'),
        ),
    ]
