# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0023_auto_20190923_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerFieldEnumeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layername', models.CharField(max_length=150)),
                ('schema', models.CharField(max_length=150)),
                ('field', models.CharField(max_length=150)),
                ('enumeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Enumeration')),
                ('lyrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Layer')),
            ],
        ),
    ]
