# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-25 08:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_worldwind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldwindprovider',
            name='heightUrl',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='worldwindprovider',
            name='type',
            field=models.CharField(default='url', max_length=250),
        ),
    ]
