# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-14 10:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0002_workspace_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='highlight_scale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
