# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-20 12:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0029_layer_default_srs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='default_srs',
        ),
    ]
