# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-27 16:38


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0034_layerfieldenumeration_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerfieldenumeration',
            name='layername',
        ),
        migrations.RemoveField(
            model_name='layerfieldenumeration',
            name='schema',
        ),
    ]
