# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-20 14:47


from django.db import migrations
import ast, json
from gvsigol_services.backend_postgis import Introspect


def get_db_connect_from_datastore(datastore):
    params = json.loads(datastore.connection_params)
    host = params['host']
    port = params['port']
    dbname = params['database']
    user = params['user']
    passwd = params['passwd']
    i = Introspect(database=dbname, host=host, port=port, user=user, password=passwd)
    return i, params.get('schema', 'public')

def has_field(layer, field_name):
    layer_conf = ast.literal_eval(layer.conf) if layer.conf else {}
    fields = layer_conf.get('fields', [])
    for field in fields:
        if field.get('name') == field_name:
            return True
    return False

def install(trigger):
    # model methods can't be used from migrations
    trigger_name = get_name(trigger)
    i, target_schema = get_db_connect_from_datastore(trigger.layer.datastore)
    target_table = trigger.layer.source_name if trigger.layer.source_name else trigger.layer.name
    i.install_trigger(trigger_name, target_schema, target_table,
                    trigger.procedure.activation, trigger.procedure.event, trigger.procedure.orientation, '', trigger.procedure.func_schema, trigger.procedure.func_name, [trigger.field])
    i.close()

def drop(trigger):
    trigger_name = get_name(trigger)
    i, target_schema = get_db_connect_from_datastore(trigger.layer.datastore)
    target_table = trigger.layer.source_name if trigger.layer.source_name else trigger.layer.name
    i.drop_trigger(trigger_name, target_schema, target_table)
    i.close()

def get_name(trigger):
    return trigger.procedure.func_name + "_" + trigger.field + "_trigger"

def fix_triggers(apps, schema_editor):
    try:
        Trigger = apps.get_model("gvsigol_services", "Trigger")
        for trigger in Trigger.objects.all():
            if trigger.field.lower() != trigger.field and trigger.layer:
                if not has_field(trigger.layer, trigger.field):
                    drop(trigger)
                    if has_field(trigger.layer, trigger.field.lower()):
                        trigger.field = trigger.field.lower()
                        trigger.save()
                        install(trigger)
                    else:
                        trigger.delete()
    except Exception as error:
        import logging
        logger = logging.getLogger()
        #logging.basicConfig()
        logger.exception(str(error))
        print(error)
        
class Migration(migrations.Migration):
    dependencies = [
        ('gvsigol_services', '0045_golfunc_geocoder_inv_icv_gva_es'),
    ]

    operations = [
        migrations.RunPython(fix_triggers, reverse_code=migrations.RunPython.noop),
    ]
