# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-10-20 14:47


from django.db import migrations
import ast, json

def set_external_layers_as_public(apps, schema_editor):
    try:
        Layer = apps.get_model("gvsigol_services", "Layer")
        for layer in Layer.objects.filter(external=True):
            layer.public = True
            layer.save()
    except Exception as error:
        import logging
        logger = logging.getLogger()
        #logging.basicConfig()
        logger.exception(str(error))
        print(error)
        
class Migration(migrations.Migration):
    dependencies = [
        ('gvsigol_services', '0049_auto_20210222_1626'),
    ]

    operations = [
        migrations.RunPython(set_external_layers_as_public, reverse_code=migrations.RunPython.noop),
    ]
