# Generated by Django 2.2.28 on 2023-07-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0058_defaultuserdatastore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuserdatastore',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
