# Generated by Django 2.2.28 on 2024-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0066_auto_20240405_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='featureapi_endpoint',
            field=models.CharField(default='/api/v1', max_length=100),
        ),
    ]
