# Generated by Django 2.2.28 on 2024-11-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0068_fix_lyr_title_valtrans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerresource',
            name='feature',
            field=models.BigIntegerField(),
        ),
    ]
