# Generated by Django 2.2.28 on 2025-05-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0071_marker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='order',
        ),
        migrations.AddField(
            model_name='marker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
