# Generated by Django 2.2.28 on 2025-07-23 13:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_services', '0073_auto_20250527_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerTopologyConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_overlap', models.BooleanField(default=False)),
                ('no_gaps', models.BooleanField(default=False)),
                ('must_be_covered_by', models.BooleanField(default=False)),
                ('covered_by_layer', models.CharField(blank=True, help_text='Capa que debe cubrir en formato datastore:tabla', max_length=255, null=True)),
                ('must_not_overlap_with', models.BooleanField(default=False)),
                ('overlap_layers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Lista de capas con las que no debe solapar en formato datastore:tabla')),
                ('must_be_contiguous', models.BooleanField(default=False)),
                ('contiguous_tolerance', models.FloatField(default=1.0, help_text='Tolerancia en metros para la contigüidad')),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topology_config', to='gvsigol_services.Layer')),
            ],
            options={
                'verbose_name': 'Layer Topology Configuration',
                'verbose_name_plural': 'Layer Topology Configurations',
            },
        ),
    ]
