# Generated by Django 2.2.28 on 2025-10-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_core', '0051_update_viewer_preferred_ui_choices'),
        ('gvsigol_services', '0078_enumeration_show_first_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='gvsigol_core.Project'),
        ),
    ]
