# Generated by Django 2.2.28 on 2023-11-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_filemanager', '0005_auto_20230405_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exports_historical',
            name='file',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exports_historical',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
