# Generated by Django 2.2.18 on 2021-08-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_trip_planner', '0003_gtfsstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtfsstatus',
            name='id_ws',
        ),
    ]
