# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-11 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_auth', '0001_initial'),
        ('gvsigol_plugin_survey', '0002_auto_20180104_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_plugin_survey.Survey')),
                ('user_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gvsigol_auth.UserGroup')),
            ],
        ),
    ]
