# -*- coding: utf-8 -*-
APP_TITLE = 'Gestor de descargas'
APP_DESCRIPTION = 'Gestor de descargas'
TMP_DIR='##DOWNLOADMANAGER_TMP_DIR##'
TARGET_ROOT='##DOWNLOADMANAGER_TARGET_ROOT##'
TARGET_URL = '##DOWNLOADMANAGER_TARGET_URL##'
DOWNLOADS_URL = '##DOWNLOADS_URL##'
DOWNLOADS_ROOT = '##DOWNLOADMANAGER_DOWNLOADS_ROOT##'
LOCAL_PATHS_WHITELIST = [##DOWNLOADMANAGER_LOCAL_PATHS_WHITELIST##]