# -*- coding: utf-8 -*-
APP_TITLE = 'Gestor de descargas'
APP_DESCRIPTION = 'Gestor de descargas'
TMP_DIR='##DOWNMAN_TMP_DIR##'
TARGET_ROOT='##DOWNLOADMANAGER_TARGET_ROOT##'
TARGET_URL = '##DOWNLOADMANAGER_BASE_URL##/'
LOCAL_PATHS_WHITELIST = [##LOCAL_PATHS_WHITELIST##]