# Generated by Django 2.2.18 on 2023-01-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0010_segex_fechafingarantizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segex_fechafingarantizada',
            name='project',
        ),
    ]
