# Generated by Django 2.2.28 on 2023-06-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0015_auto_20230627_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etlstatus',
            name='id_ws',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etlworkspaces',
            name='concat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
