# Generated by Django 2.2.28 on 2023-06-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0016_auto_20230627_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etlworkspaces',
            name='concat',
            field=models.BooleanField(default=False),
        ),
    ]
