# Generated by Django 2.2.28 on 2023-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0018_auto_20230719_1046'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='etlworkspaceeditrole',
            constraint=models.UniqueConstraint(fields=('etl_ws', 'role'), name='unique_edit_permission_per_role_and_etlws'),
        ),
        migrations.AddConstraint(
            model_name='etlworkspaceexecuterole',
            constraint=models.UniqueConstraint(fields=('etl_ws', 'role'), name='unique_exec_permission_per_role_and_etlws'),
        ),
    ]
