# Generated by Django 2.2.28 on 2025-04-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_geoetl', '0024_auto_20240626_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempETLTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tabla Temporal de ETL',
                'verbose_name_plural': 'Tablas Temporales de ETL',
            },
        ),
    ]
