from gvsigol.settings import GVSIGOL_AUTH_BACKEND
OIDC_RP_CLIENT_ID = ''
OIDC_RP_CLIENT_SECRET = ''
OIDC_OP_AUTHORIZATION_ENDPOINT = ''
OIDC_OP_TOKEN_ENDPOINT = ''
OIDC_OP_USER_ENDPOINT = ''
OIDC_OP_JWKS_ENDPOINT = ''
OIDC_OP_LOGOUT_ENDPOINT = ''
OIDC_OP_LOGOUT_URL_METHOD = GVSIGOL_AUTH_BACKEND + ".provider_logout"
OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_STORE_ACCESS_TOKEN = True
OIDC_STORE_ID_TOKEN = True
OIDC_RP_SCOPES = 'openid email username geoserver-client'
KEYCLOAK_ADMIN_CLIENT_ID = ''
KEYCLOAK_ADMIN_CLIENT_SECRET = ''
KEYCLOAK_ADMIN_BASE_URL = ''
