# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0008_auto_20191001_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='prepared_download_path',
            field=models.FilePathField(max_length=1000),
        ),
    ]
