# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-18 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_downloadman', '0024_auto_20200212_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlink',
            name='resolved_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
