# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gvsigol_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Layer')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LibrarySymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('sld_code', models.CharField(blank=True, max_length=5000, null=True)),
                ('type', models.CharField(default='PointSymbolizer', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_symbology.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('filter', models.CharField(blank=True, max_length=5000, null=True)),
                ('order', models.IntegerField(default=0)),
                ('minscale', models.FloatField(blank=True, null=True)),
                ('maxscale', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_symbology.Rule')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('SU', 'Simbolo_unico'), ('VU', 'Valores_unicos'), ('IN', 'Intervalos'), ('EX', 'Expresiones'), ('TC', 'Tabla de color'), ('CH', 'Graficas')], default='SU', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('sld_code', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rulesymbol',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_symbology.Symbol'),
        ),
        migrations.AddField(
            model_name='rule',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_symbology.Style'),
        ),
        migrations.AddField(
            model_name='layerstyle',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_symbology.Style'),
        ),
    ]
