# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gvsigol_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_symbology.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=25)),
                ('filter', models.CharField(blank=True, max_length=5000, null=True)),
                ('minscale', models.FloatField(blank=True, null=True)),
                ('maxscale', models.FloatField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('US', 'Unique symbol'), ('UV', 'Unique values'), ('IN', 'Intervals'), ('EX', 'Expressions'), ('CT', 'Color table'), ('CH', 'Graphics')], default='US', max_length=2)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StyleLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_services.Layer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_symbology.Style')),
            ],
        ),
        migrations.CreateModel(
            name='StyleRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_symbology.Rule')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_symbology.Style')),
            ],
        ),
        migrations.CreateModel(
            name='Symbolizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('sld', models.CharField(blank=True, max_length=5000, null=True)),
                ('json', models.CharField(blank=True, max_length=5000, null=True)),
                ('order', models.IntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_symbology.Rule')),
            ],
        ),
        migrations.AddField(
            model_name='libraryrule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvsigol_symbology.Rule'),
        ),
    ]
