# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-23 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_symbology', '0004_auto_20171017_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='type',
            field=models.CharField(choices=[('US', 'S\xedmbolo \xfanico'), ('UV', 'Valores \xfanicos'), ('IN', 'Intervalos'), ('EX', 'Expresiones'), ('CP', 'Clustered Points'), ('CT', 'Tabla de color'), ('CH', 'Gr\xe1ficas')], default='US', max_length=2),
        ),
    ]
