# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-12 10:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_symbology', '0007_auto_20171205_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='type',
            field=models.CharField(choices=[('US', 'Unique symbol'), ('UV', 'Unique values'), ('IN', 'Intervals'), ('EX', 'Expressions'), ('CP', 'Clustered Points'), ('CT', 'Color table'), ('CH', 'Graphics')], default='US', max_length=2),
        ),
    ]
