# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-02-01 13:49


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GTFSProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.URLField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
