# Generated by Django 2.2.18 on 2021-07-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvsigol_plugin_trip_planner', '0002_appmobileconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTFSstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('id_ws', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
